mongo:
  image: mongo
  ports:
    - "27017:27017"

storage:
  image: java:alpine
  volumes:
    - ./storage/build/libs/storage-1.0-SNAPSHOT.jar:/var/app.jar:Z
  command: java -jar /var/app.jar -cluster
  links:
    - mongo
    - logstash

#bc-service:
#  image: java:alpine
#  volumes:
#    - ./bc-service/build/libs/bc-service-1.0-SNAPSHOT.jar:/var/app.jar:Z
#  command: java -jar /var/app.jar -cluster
#  links:
#    - logstash

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -E Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash
  command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
            output { elasticsearch { hosts => ["elasticsearch"] } }'
  links:
    - elasticsearch
  ports:
    - "12201:12201/udp"

kibana:
  image: kibana
  ports:
    - "5601:5601"
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch
    - logstash

web:
  image: java:alpine
  volumes:
    - ./web/build/libs/web-1.0-SNAPSHOT.jar:/var/app.jar:Z
  command: java -jar /var/app.jar -cluster
  ports:
    - "80:8000"
  links:
    - logstash
