global:
  scrape_interval:      15s
  evaluation_interval:  15s
  
scrape_configs:
  - job_name: 'web'
    scrape_interval:  5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'
    static_configs:
      - targets: ['web:8000']
    