#%RAML 0.8
title: Hello world REST API
baseUri: http://localhost
version: v1
/utx/{skip}/{limit}:
  uriParameters:
    skip:
      description: number of UTX to skip
    limit:
      description: number of UTX to return (excluding the skiped ones)
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              { "$schema": "http://json-schema.org/schema",
                "type": "array",
                "description": "Unconfirmed TX"
              }